name: Publish to npm (Dry Run)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version in package.json
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          VERSION_NUMBER="${VERSION#v}"
          yarn version --new-version $VERSION_NUMBER --no-git-tag-version

      - name: Push version bump
        run: |
          git push origin HEAD:${{ github.ref }}

      - name: Publish to npm (Dry Run)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --dry-run
