name: Test E2E
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}

      - name: tests
        run: yarn test-e2e
        env:
          ORIGINAL_API_KEY: ${{secrets.ORIGINAL_API_KEY}}
          ORIGINAL_API_SECRET: ${{secrets.ORIGINAL_API_SECRET}}
          ORIGINAL_BASE_URL: ${{secrets.ORIGINAL_BASE_URL}}
          TEST_ALLOCATION_UID: ${{secrets.TEST_ALLOCATION_UID}}
          TEST_APP_USER_EMAIL: ${{secrets.TEST_APP_USER_EMAIL}}
          TEST_APP_USER_UID: ${{secrets.TEST_APP_USER_UID}}
          TEST_APP_USER_USER_EXTERNAL_ID: ${{secrets.TEST_APP_USER_USER_EXTERNAL_ID}}
          TEST_ASSET_UID: ${{secrets.TEST_ASSET_UID}}
          TEST_CLAIM_TO_ADDRESS: ${{secrets.TEST_CLAIM_TO_ADDRESS}}
          TEST_CLAIM_UID: ${{secrets.TEST_CLAIM_UID}}
          TEST_COLLECTION_UID: ${{secrets.TEST_COLLECTION_UID}}
          TEST_REWARD_UID: ${{secrets.TEST_REWARD_UID}}
          TEST_TRANSFER_TO_USER_UID: ${{secrets.TEST_TRANSFER_TO_USER_UID}}
          TEST_TRANSFER_TO_WALLET_ADDRESS: ${{secrets.TEST_TRANSFER_TO_WALLET_ADDRESS}}
